config/routes.rb
::Refinery::Application.routes.draw do
  resources :event_venues, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :event_venues, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
end

app/models/event_venue.rb
class EventVenue < ActiveRecord::Base

  acts_as_indexed :fields => [:venue_name, :venue_address]

  validates :venue_name, :venue_address, :presence => true
end

app/controllers/admin/event_venues_controller.rb
module Admin
  class EventVenuesController < Admin::BaseController

    crudify :event_venue,
            :title_attribute => 'venue_name', :xhr_paging => true

  end
end

app/controllers/event_venues_controller.rb
class EventVenuesController < ApplicationController

  before_filter :find_all_event_venues
  before_filter :find_page

  def index
    # you can use meta fields from your model instead (e.g. browser_title)
    # by swapping @page for @event_venue in the line below:
    present(@page)
  end

  def show
    @event_venue = EventVenue.find(params[:id])

    # you can use meta fields from your model instead (e.g. browser_title)
    # by swapping @page for @event_venue in the line below:
    present(@page)
  end

protected

  def find_all_event_venues
    @event_venues = EventVenue.order('position ASC')
  end

  def find_page
    @page = Page.where(:link_url => "/event_venues").first
  end

end

app/views/admin/event_venues/_actions.html.erb
<ul>
  <% if Admin::EventVenuesController.searchable? %>
    <li>
      <%= render :partial => "/shared/admin/search",
                  :locals => {
                    :url => admin_event_venues_path
                  } %>
    </li>
  <% end %>
  <li>
    <%= link_to t('.create_new'), new_admin_event_venue_path,
                 :class => "add_icon" %>
  </li>
<% if !searching? and Admin::EventVenuesController.sortable? and EventVenue.count > 1 %>
  <li>
    <%= link_to t('.reorder', :what => "EventVenues"),
                 admin_event_venues_path,
                 :id => "reorder_action",
                 :class => "reorder_icon" %>

    <%= link_to t('.reorder_done', :what => "EventVenues"),
                 admin_event_venues_path,
                 :id => "reorder_action_done",
                 :style => "display: none;",
                 :class => "reorder_icon" %>
  </li>
<% end %>
</ul>

app/views/admin/event_venues/_event_venue.html.erb
<li class='clearfix record <%= cycle("on", "on-hover") %>' id="<%= dom_id(event_venue) -%>">
  <span class='title'>
    <%= event_venue.venue_name %>
    <span class="preview">&nbsp;</span>
  </span>
  <span class='actions'>
    <%= link_to refinery_icon_tag("application_go.png"), event_venue_path(event_venue),
        :title => t('.view_live_html'),
        :target => "_blank" %>
    <%= link_to refinery_icon_tag("application_edit.png"), edit_admin_event_venue_path(event_venue),
         :title => t('.edit') %>
    <%= link_to refinery_icon_tag("delete.png"), admin_event_venue_path(event_venue),
        :class => "cancel confirm-delete",
        :title => t('.delete'),
        :confirm => t('message', :scope => 'shared.admin.delete', :title => event_venue.venue_name),
        :method => :delete %>
  </span>
</li>

app/views/admin/event_venues/_event_venues.html.erb
<%= will_paginate @event_venues %>
<%= render :partial => "sortable_list" %>

app/views/admin/event_venues/_form.html.erb
<%= form_for [:admin, @event_venue] do |f| -%>
  <%= render :partial => "/shared/admin/error_messages", :locals => {
          :object => @event_venue,
          :include_object_name => true
        } %>
  
  <div class='field'>
    <%= f.label :venue_name -%>
    <%= f.text_field :venue_name, :class => 'larger widest'  -%>
  </div>
  
  <div class='field'>
    <%= f.label :venue_address -%>
    <%= f.text_field :venue_address  -%>
  </div>
  
  <div class='field'>
    <%= f.label :venue_calendar_color -%>
    <%= f.text_field :venue_calendar_color  -%>
  </div>
 
  <%= render :partial => "/shared/admin/form_actions",
              :locals => {
                :f => f,
                :continue_editing => false,
                :delete_title => t('delete', :scope => 'admin.event_venues.venue'),
                :delete_confirmation => t('message', :scope => 'shared.admin.delete', :title => @event_venue.venue_name)
              } %>
<% end -%>

app/views/admin/event_venues/_records.html.erb
<% if searching? %>
  <h2><%= t('results_for', :scope => 'shared.admin.search', :query => params[:search]) %></h2>
<% end %>
<% if @event_venues.any? %>
  <div class='pagination_container'>
    <%= render :partial => 'event_venues' %>
  </div>
<% else %>
  <p>
    <% unless searching? %>
      <strong>
        <%= t('.no_items_yet') %>
      </strong>
    <% else %>
      <%= t('no_results', :scope => 'shared.admin.search') %>
    <% end %>
  </p>
<% end %>

app/views/admin/event_venues/_sortable_list.html.erb
<ul id='sortable_list'>
  <%= render :partial => 'event_venue', :collection => @event_venues %>
</ul>
<%= render :partial => "/shared/admin/sortable_list",
            :locals => {
              :continue_reordering => (local_assigns.keys.include?(:continue_reordering)) ? continue_reordering : true
            } %>

app/views/admin/event_venues/edit.html.erb
<%= render :partial => "form" %>

app/views/admin/event_venues/index.html.erb
<section id='records'>
  <%= render :partial => 'records' %>
</section>
<aside id='actions'>
  <%= render :partial => 'actions' %>
</aside>
<%= render :partial => '/shared/admin/make_sortable',
            :locals => {
              :tree => false
            } if !searching? and Admin::EventVenuesController.sortable? and EventVenue.count > 1 %>

app/views/admin/event_venues/new.html.erb
<%= render :partial => "form" %>

app/views/event_venues/index.html.erb
<% content_for :body_content_left do %>
  <ul id="event_venues">
    <% @event_venues.each do |event_venue| %>
      <li>
        <%= link_to event_venue.venue_name, event_venue_path(event_venue) %>
      </li>
    <% end %>
  </ul>
<% end %>

<%= render :partial => "/shared/content_page" %>

app/views/event_venues/show.html.erb
<% content_for :body_content_title do %>
  <%= @event_venue.venue_name %>
<% end %>

<% content_for :body_content_left do %>
  <section>
    <h1>Venue Name</h1>
    <p>
      <%=raw @event_venue.venue_name %>
    </p>
  </section>
  <section>
    <h1>Venue Address</h1>
    <p>
      <%=raw @event_venue.address %>
    </p>
  </section>
  <section>
    <h1>Venue Calendar Color</h1>
    <p>
      <%=raw @event_venue.calendar_color %>
    </p>
  </section>
<% end %>

<% content_for :body_content_right do %>
  <aside>
    <h2><%= t('.other') %></h2>
    <ul id="event_venues">
      <% @event_venues.each do |event_venue| %>
        <li>
          <%= link_to event_venue.venue_name, event_venue_path(event_venue) %>
        </li>
      <% end %>
    </ul>
  </aside>
<% end %>

<%= render :partial => "/shared/content_page" %>